version: "3.8"

services:

  fin-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: fin-app
    command: python run.py
    volumes:
      - ./src:/home/finapp
    tty: true
    restart: on-failure


networks:
  finappwb-network:
    external: false