name: Test and Build

on:
  push:
    branches:
      - main

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install pycodestyle
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle

      - name: Check codestyle
        run: pycodestyle ./src/*.py

  build_deploy:
    needs: [run_test]
    runs-on: ubuntu-latest
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
    steps:
      - name: Login to docker
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin

      - uses: actions/checkout@v2

      - name: Build and tag image
        run: |
          make build
          docker tag finappwb_fin-app $LOGIN/$NAME:${GITHUB_REF:11}
      - name: Push image to DockerHub
        run:
          docker push $LOGIN/$NAME:${GITHUB_REF:11}

  deploy_to_server:
    needs: [build_deploy]
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
    steps:
      - uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USERNAME }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            docker stop fin-app;
            docker pull $LOGIN/$NAME:${GITHUB_REF:11}
            docker run -d $LOGIN/$NAME:${GITHUB_REF:11}
        
